---
- name: Create an S3 bucket
  s3: 
    bucket: "{{s3_bucket_name}}"
    mode: create 
    permission: public-read
    region: "{{region}}"
    aws_access_key: "{{aws_access_key}}"
    aws_secret_key: "{{aws_secret_key}}"

- name: Encrypt the S3 bucket with a bucket policy
  s3_bucket:
    name: "{{s3_bucket_name}}"
    policy: "{{lookup('file','policy.json')}}"
    aws_access_key: "{{aws_access_key}}"
    aws_secret_key: "{{aws_secret_key}}"

- name: Upload data to the encrypted S3 bucket
  s3:
    bucket: "{{s3_bucket_name}}"
    mode: put
    encrypt: yes
    permission: public-read
    aws_access_key: "{{aws_access_key}}"
    aws_secret_key: "{{aws_secret_key}}"
    object: "{{item.object}}"
    src: "{{item.src}}"
  with_items:
    - {object: index.html, src: roles/s3/files/index.html}
    - {object: error.html, src: roles/s3/files/error.html}

- name: Set up the static website
  command: "aws s3 website s3://{{s3_bucket_name}}/ --index-document index.html --error-document error.html"