---
- name: Check if data has been uploaded to S3 bucket
  command: bash -c "aws s3 ls s3://{{ bucket_name }} | grep {{ item }}"
  with_items:
    - index.html
    - error.html
  register: data_uploaded
  ignore_errors: True
  tags:
    - s3_upload

- name: Upload data to the encrypted S3 bucket
  s3:
    bucket: "{{ bucket_name }}"
    mode: put
    encrypt: yes
    permission: public-read
    aws_access_key: "{{aws_access_key}}"
    aws_secret_key: "{{aws_secret_key}}"
    object: "{{item.object}}"
    src: "{{item.src}}"
  with_items:
    - {object: index.html, src: roles/s3/files/index.html}
    - {object: error.html, src: roles/s3/files/error.html}
  when: data_uploaded|failed
  tags:
    - s3_upload
