---
- name: Pause playbook to allow newly created ami to propagate
  pause: minutes=1
  tags:
    - j2_json

- name: Get created ami's ID
  ec2_ami_find:
    name: "{{ ami_name }}"
    region: "{{ region }}"
    sort: name
    sort_order: descending
    sort_end: 1
  register: created_ami_id
  tags:
    - j2_json

- name: Convert cloudformation template from j2 to json
  local_action: template src=roles/cloudformation/templates/cloudformation.json.j2 dest=roles/cloudformation/templates/cloudformation.json
  tags:
    - j2_json

- name: Configure AWS infrastructure using Cloudformation
  cloudformation:
    stack_name: "{{ cf_stack_name }}"
    state: "present"
    region: "{{region}}"
    disable_rollback: true
    template: "roles/cloudformation/templates/cloudformation.json"
    aws_access_key: "{{ aws_access_key }}"
    aws_secret_key: "{{ aws_secret_key }}"
    tags:
      Stack: "{{cf_tag}}"
  register: cloudformation
  tags:
    - cloudformation