---
- name: Check if a launch configuration with the same name as the launch_config_name variable already exists
  command: bash -c "aws autoscaling describe-launch-configurations --launch-configuration-names | grep '{{launch_config_name}}'"
  register: launch_config_created
  ignore_errors: true

- name: Create launch configuration using the ami created
  ec2_lc:
    name: "{{launch_config_name}}"
    image_id: "{{ami.image_id}}"
    region: "{{region}}"
    instance_type: t2.micro
    assign_public_ip: no
    aws_access_key: "{{aws_access_key}}"
    aws_secret_key: "{{aws_secret_key}}"
  when: launch_config_created|failed

- name: Create an auto scaling group from the launch config above
  ec2_asg:
    name: "{{asg_name}}"
    launch_config_name: "{{launch_config_name}}"
    min_size: 2
    max_size: 4
    desired_capacity: 2
    region: "{{region}}"
    health_check_period: 60
    health_check_type: ELB
    vpc_zone_identifier: [ "{{cloudformation.stack_resources[2].physical_resource_id}}", "{{cloudformation.stack_resources[6].physical_resource_id}}" ]
    aws_access_key: "{{aws_access_key}}"
    aws_secret_key: "{{aws_secret_key}}"
    tags:
    - environment: dev
  when: launch_config_created|failed